### ISSUE TITLE
Cannot differentiate between failed DNSSEC and unsigned

### ISSUE THREAD

**Issue by pzb** [alexdalitz/dnsruby#87]
The security_level is INSECURE both for DNSSEC failures (bad signature) and when there is no DNSSEC info available.  These should be two different levels.

```ruby
require 'dnsruby'
require 'pp'

rec = Dnsruby::Recursor.new
rec.hints = ["198.41.0.4","192.228.79.201","192.33.4.12","199.7.91.13","192.203.230.10","192.5.5.241","192.112.36.4","128.63.2.53","192.36.148.17","192.58.128.30","193.0.14.129","199.7.83.42","202.12.27.33"]

pp rec.query("www.dnssec-failed.org")
pp rec.query("www.amazon.com")
```

**Comment by alexdalitz** [comment]
Hi Peter - 

Thanks for this report.
You're right that the dnssec-failed.org security level should be BOGUS. There is currently a bug whereby, if the security chain can't be followed, the level is set to INSECURE. I will look at fixing this so that INSECURE is returned where there is no DS chain, and BOGUS is returned where the chain is broken.
I'll try to do this later today, or else tomorrow.
Thanks,

Alex.

**Comment by alexdalitz** [comment]
Hi - 

This is now fixed in master. Could you please let me know if you have any problems?

Thanks!

Alex.

**Comment by pzb** [comment]
It now is reporting BOGUS for www.amazon.com, where is should be INSECURE.

**Comment by alexdalitz** [comment]
Doh! Sorry about this. I'll try to find a little more time to look at it next time!

**Comment by alexdalitz** [comment]
Hi - 

This is now fixed.
Thanks!

Alex.
