### ISSUE TITLE
dnsruby queries localhost when invalid name server specified

### ISSUE THREAD

**Issue by mrideout** [alexdalitz/dnsruby#89]
First of all, thank you for creating dnsruby! I've using it for monitoring DNS records, and have been really happy with its flexibility.

If I query a name server by hostname, and that hostname cannot be resolved, then dnsruby tries to query localhost instead.

Here are the steps to reproduce:

require 'dnsruby'
resolver = Dnsruby::Resolver.new
resolver.do_caching = false
resolver.dnssec = false
resolver.config.nameserver = ['no-such-nameserver.example.com']
resolver.query('example.com', 'a')

This means that if I try to query an invalid name server from a host which is not running a resolver on localhost, I get this error message:

Dnsruby::OtherResolvError: recvfrom failed from ; Connection refused - recvfrom(2)

If I do the same thing from a system which is running a resolver on localhost, then dnsruby queries it, and returns its results:

 => #<Dnsruby::Message:0x007f81781d0cd0 @header=#<Dnsruby::Header:0x007f81781d06e0 @id=59590, @qr=true, @opcode=Query, @aa=false, @ad=false, @tc=false, @rd=true, @ra=true, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=2, @ancount=1, @arcount=4>, @question=[#<Dnsruby::Question:0x007f81781cfba0 @qtype=A, @qclass=IN, @qname=#<Dnsruby::Name: example.com.>>], @answer=[#<Dnsruby::RR::IN::A:0x007f81781cf010 @rdata=#<Dnsruby::IPv4 93.184.216.34>, @address=#<Dnsruby::IPv4 93.184.216.34>, @name=#<Dnsruby::Name: example.com.>, @ttl=60, @type=A, @klass=IN>], @authority=[#<Dnsruby::RR::IN::NS:0x007f81781cdcd8 @rdata=#<Dnsruby::Name: b.iana-servers.net.>, @domainname=#<Dnsruby::Name: b.iana-servers.net.>, @name=#<Dnsruby::Name: example.com.>, @ttl=57, @type=NS, @klass=IN>, #<Dnsruby::RR::IN::NS:0x007f81781cc6a8 @rdata=#<Dnsruby::Name: a.iana-servers.net.>, @domainname=#<Dnsruby::Name: a.iana-servers.net.>, @name=#<Dnsruby::Name: example.com.>, @ttl=57, @type=NS, @klass=IN>], @additional=[#<Dnsruby::RR::IN::A:0x007f81781cb500 @rdata=#<Dnsruby::IPv4 199.43.132.53>, @address=#<Dnsruby::IPv4 199.43.132.53>, @name=#<Dnsruby::Name: a.iana-servers.net.>, @ttl=57, @type=A, @klass=IN>, #<Dnsruby::RR::IN::AAAA:0x007f81781ca3d0 @rdata=#<Dnsruby::IPv6 2001:500:8C::53>, @address=#<Dnsruby::IPv6 2001:500:8C::53>, @name=#<Dnsruby::Name: a.iana-servers.net.>, @ttl=57, @type=AAAA, @klass=IN>, #<Dnsruby::RR::IN::A:0x007f81781c94d0 @rdata=#<Dnsruby::IPv4 199.43.133.53>, @address=#<Dnsruby::IPv4 199.43.133.53>, @name=#<Dnsruby::Name: b.iana-servers.net.>, @ttl=57, @type=A, @klass=IN>, #<Dnsruby::RR::IN::AAAA:0x007f81781c85d0 @rdata=#<Dnsruby::IPv6 2001:500:8D::53>, @address=#<Dnsruby::IPv6 2001:500:8D::53>, @name=#<Dnsruby::Name: b.iana-servers.net.>, @ttl=57, @type=AAAA, @klass=IN>], @tsigstate=:Unsigned, @signing=false, @tsigkey=nil, @answerfrom="127.0.0.1", @answerip="127.0.0.1", @send_raw=false, @do_validation=true, @do_caching=true, @security_level=UNCHECKED, @security_error=nil, @cached=false, @answersize=181>

My expectation is that if an invalid name server is specified, dnsruby will return an error message, indicating that.

Is this an issue with dnsruby, or am I using it incorrectly?

Thanks,

Matt

**Comment by alexdalitz** [comment]
Hi - 

Thanks for your clear problem report.

When you configure dnsruby with nameserver names, it needs to resolve the names into IP addresses. 
It does this lazily, which means that you won't get an error report if you give it an invalid name - it tries its best to resolve the name in the background. This means that we can't give an error as soon as the invalid name is configured.

Since you have given dnsruby a domain name to resolve (for the nameserver), it needs to configure itself with the system-wide resolvers (configured in /etc/resolv.conf) in order to resolve this name. It is trying to do this, but failing, when you ask it to resolve the query name.
I accept that the current system is surprising - but I would be interested to know what you might expect to happen in this case?

Thanks!

Alex.

**Comment by mrideout** [comment]
Hi Alex,

If a name, rather than IP address is given for a nameserver, then dnsruby's current behavior of attempting to resolve that name using the system wide resolvers makes sense.

If the system wide resolvers do not return a usable response, then I would expect dnsruby to return an error, rather than run the requested DNS query on localhost.

A parallel to this is what happens if you try to query a nameserver by IP, and that IP isn't responsive. When this happens, `Dnsruby::ResolvTimeout: Query timed out` is returned.

Could dnsruby do the following when asked to query a nameserver whose name can't be resolved to an IP?

1. Attempt to resolv the nameserver and fais.
2. Return `Dnsruby::NXDomain: No such nameserver`, instead of attempting to resolv the requested record.

Thanks,

Matt

**Comment by keithrbennett** [comment]
Alex, is this what Resolver.send_plain_message and Resolver.query_raw already address?

**Comment by alexdalitz** [comment]
Hi Matt - 


> Could dnsruby do the following when asked to query a nameserver whose name can't be resolved to an IP?
> Attempt to resolv the nameserver and fais.
> Return Dnsruby::NXDomain: No such nameserver, instead of attempting to resolv the requested record.
Sounds reasonable, except that NXDomain really means that the domain doesn’t exist. In this case, the domain may well exist, but the name server we asked dnsruby to use to resolve it does not.

I agree that querying localhost is unexpected behaviour. I’ll look into changing the code so that no nameservers are configured, if the given nameserver is not resolvable. In that case, the query will fail because no name servers are configured, which is probably not an unreasonable outcome.

I’ll try to do this in the next day or two.

Thanks,


Alex Dalitz
alex@caerkettontech.com

**Comment by mrideout** [comment]
Thanks, Alex!

**Comment by alexdalitz** [comment]
Hi Matt - 

Are you able to check the current code in the git repository, please?

Thanks,


Alex.

> On 7 Sep 2015, at 17:24, Matt Rideout <notifications@github.com> wrote:
> 
> Thanks, Alex!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/alexdalitz/dnsruby/issues/89#issuecomment-138335279>.
> 


Alex Dalitz
alex@caerkettontech.com

**Comment by mrideout** [comment]
Hi Alex,

This looks great. I checked out a copy, and verified that it works as I'd expect.

Thanks,

Matt
